// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElMenu: typeof import('element-plus/es')['ElMenu'];
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
    Header: typeof import('./src/components/Header/index.vue')['default'];
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
  }
}

export {};
